apis/v1beta1/microk8sconfig_types.go, apis/v1beta1/zz_generated.deepcopy.go, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml, controllers/microk8sconfig_controller.go, examples/aws-capi-quickstart.yaml, examples/openstack-capi-quickstart.yaml
This PR removes the BootstrapToken struct from the config specs and the corresponding logic from the controller.
Verified that the cluster is provisioned correctly:
```bash
$ kubectl get clusters
NAME                  PHASE         AGE   VERSION
capi-aws-19072022-4   Provisioned   30m   
$ kubectl get machines
NAME                                      CLUSTER               NODENAME         PROVIDERID                              PHASE     AGE   VERSION
capi-aws-19072022-4-control-plane-n5pvb   capi-aws-19072022-4   ip-10-0-182-80   aws:///us-east-1b/i-0576e23980facc680   Running   26m   v1.23.0
```
=> Remove BootstrapTokens logic

.github/workflows/go.yml, Makefile, controllers/microk8sconfig_controller.go
Hi :wave:
This pr adds a `make lint` Makefile taget that
* downloads golangci-lint 
* runs golangci-lint 
Since I've also fixed the findings that golangci-lint found. Note this is not the latest and greatest golangci-lint version but it's what worked with go1.17. I haven't added it to any workflow but maybe it's something that should be in the build.
=> Add Makefile target lint

.golangci.yaml, apis/v1beta1/microk8sconfig_types.go, apis/v1beta1/zz_generated.deepcopy.go, controllers/cloudinit/cloudinit_test.go, controllers/cloudinit/controlplane_init.go, controllers/cloudinit/controlplane_join.go, controllers/cloudinit/utils.go, controllers/cloudinit/worker_join.go, controllers/microk8sconfig_controller.go, main.go
golangci-lint has 7 linters enabled by default: 
```
- errcheck
- gosimple
- govet
- ineffassign
- staticcheck
- typecheck
- unused
```
This pr adds some additional linters that might be good to have and fixes the findings. 
```
- asciicheck
- bidichk
- contextcheck
- errchkjson
- errorlint
- exhaustive
- exportloopref
- gofmt
- makezero
- misspell
- nilerr
- prealloc
- revive
- unparam
- whitespace
```
source: https://golangci-lint.run/usage/linters
=> Enable additional linters

README.md, templates/cluster-template-aws.rc, templates/cluster-template-aws.yaml, templates/cluster-template-openstack.rc, templates/cluster-template-openstack.yaml
Add cluster templates for AWS and OpenStack. Document their usage, update the example cluster deployment in the README and make a few minor fixes.
=> Add cluster templates for AWS, OpenStack and update README

bootstrap-components.yaml, config/rbac/role.yaml, controllers/microk8sconfig_controller.go
Add RBAC rules for clusters, machines, secrets, and configmaps to the bootstrap provider. Roles are generated from kubebuilder rules in the controller code. Also re-run `make component` to update the `bootstrap-components.yaml` manifest.
1. Deploy management cluster with RBAC enabled:
```
snap install microk8s --classic
microk8s enable rbac dns
```
2. Install and configure clusterctl
3. Deploy a cluster on OpenStack and AWS (based on the cluster templates found in https://github.com/canonical/cluster-api-bootstrap-provider-microk8s/pull/22
Testing is manual for now.
=> Update RBAC rules for the bootstrap provider

Dockerfile, Makefile
Build controller images for amd64 and arm64.
```bash
make docker-build       # makes $IMG-amd64 and $IMG-arm64
make docker-manifest    # makes $IMG multi-arch image
```
A development build is pushed to `neoaggelos/capmbp:dev1`:
```bash
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 739,
"digest": "sha256:adcc532b34e03a95f11af6d740550ed83b4c61c7d7333679af8a0a231497344d",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 738,
"digest": "sha256:cd0c02ff00c37e6c4dd49e3843c7b607a5d1702419d28f59a9dcf8b18a27c660",
"platform": {
"architecture": "arm64",
"os": "linux"
}
} …
```
=> build controller images for amd64 and arm64

README.md
Point to the AWS infrastructure provider documentation for how to configure custom security groups.
=> document custom security groups

.github/workflows/release.yml
We need the full canonical name for the image or else `clusterctl` init is failing with:
```
$ clusterctl init --infrastructure "aws" --bootstrap "microk8s" --control-plane "microk8s"
Fetching providers
Error: failed to get provider components for the "microk8s" provider: failed to apply image overrides: failed to fix containers in deployment capi-microk8s-bootstrap-controller-manager: failed to fix containers: failed to fix image for container manager: couldn't parse image name: repository name must be canonical
```
=> Use the full canonical name of the docker.io repo

README.md, templates/cluster-template-aws.rc, templates/cluster-template-aws.yaml, templates/cluster-template-openstack.rc, templates/cluster-template-openstack.yaml
Add (optional) containerd http proxy configuration on OpenStack cluster template and verify it is funcional. This PR also includes some small housekeeping-related changes to the same parts of the code.
Proxy configuration was validated with the configs below, and has been fixed with the work in https://github.com/canonical/cluster-api-bootstrap-provider-microk8s/pull/39
- Add containerd http proxy configuration on openstack template
- Remove unused parts of the openstack cluster template
- Deploy kubernetes 1.25 by default
- Cleanup openstack secret generation, so that you do not need OpenStack credentials every time a cluster template is generated.
=> Add proxy configuration and cleanup cluster templates

README.md, templates/cluster-template-openstack.rc, templates/cluster-template-openstack.yaml
Fixes for the OpenStack cluster template.
- Configurable DNS nameservers for the OpenStack network. This is useful when OpenStack is using OVN, so an empty nameserver list on the network results in machines unable to resolve DNS. The list is empty by default.
- Configurable OpenStack network CIDR, useful in case of conflicts.
=> Fixes for OpenStack cluster template

apis/v1beta1/microk8sconfig_types.go, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml, controllers/cloudinit/controlplane_init.go, controllers/cloudinit/controlplane_init_test.go, controllers/cloudinit/controlplane_join.go, controllers/cloudinit/controlplane_join_test.go, controllers/cloudinit/embed.go, controllers/cloudinit/scripts/00-install-microk8s.sh, controllers/cloudinit/utils.go, controllers/cloudinit/worker_join.go, controllers/cloudinit/worker_join_test.go
**Summary**
As of now, we only installed and deployed `--classic` confined microk8s snaps in the control plane and worker nodes during bootstrapping. In microk8s, instead of the default confinement being `strict`, we use strict channels for strict confinement, like `1.25-strict`.  So, we have changed the `00-install-microk8s.sh` to take confinement as an argument, a blank argument defaults to classic, whilst giving a `"strict"` argument installs a strict snap.
Test for the same is added for `controlplane_init_test`, `controlplane_join_test`, and `worker_join_test`.
As of now, we still deploy the snaps in classic confinement but now have the option to deploy in strict mode too.
=> Add confinement option to install microk8s snaps

apis/v1beta1/microk8sconfig_types.go, controllers/cloudinit/controlplane_init.go, controllers/cloudinit/controlplane_init_test.go, controllers/cloudinit/controlplane_join.go, controllers/cloudinit/controlplane_join_test.go, controllers/cloudinit/utils.go, controllers/cloudinit/worker_join.go, controllers/cloudinit/worker_join_test.go
**Summary**
Every snap has four risk levels: stable, candidate, beta, and edge (used `--channel=<track-version>/<risk>`). This PR adds an option to add the risk levels for the version in the microk8s snap channels.
**File changes**
- apis/v1beta1/microk8sconfig_types.go: Added a new option for `RiskLevel` in the specs.
- controllers/cloudinit/*: Added the `RiskLevel` option in the init configs for `controlplane_init`, `controlplane_join`, and `worker_join`. Added corresponding tests.
=> Add option to set `risk-level` for k8s version in channel

controllers/microk8sconfig_controller.go
The `InitConfiguration` for worker nodes may be nil. In that case, make sure that we do not access things that we shouldn't.
=> Fix panics when joining worker nodes without an initConfiguration

integration/e2e_test.go
This improves the cleanup process of the e2e test.
=> Catch the exit signal and try to cleanup

controllers/cloudinit/scripts/20-microk8s-enable.sh
MicroK8s versions < 1.24 do not have a separate repository for community addons, so make sure that bootstrapping does not fail.
=> Do not fail if community addons cannot be enabled

templates/cluster-template-gcp.yaml
In the GCP cluster template, ensure we set the `publicIP` property for machine templates of the worker nodes, same as we do for the control plane.
=> gcp: ensure worker nodes publicIP is set

templates/cluster-template-aws.rc, templates/cluster-template-aws.yaml, templates/cluster-template-azure.rc, templates/cluster-template-azure.yaml, templates/cluster-template-gcp.rc, templates/cluster-template-gcp.yaml, templates/cluster-template-openstack.rc, templates/cluster-template-openstack.yaml
**Summary**
Based on: https://github.com/canonical/cluster-api-control-plane-provider-microk8s/pull/35
After updating our control plane specs with the new filed `upgradeStrategy` we also need to update our cloud templates to reflect the change. This field takes in two values: `RollingUpgrades` and `InPlaceUpgrade`, and updates the nodes and machine based on the type of upgrade specified, `RolloutUpgrades` being the default.
=> Update cloud templates with upgrade strategy field

controllers/cloudinit/controlplane_init_test.go, controllers/microk8sconfig_controller.go, templates/cluster-template-aws.rc, templates/cluster-template-aws.yaml, templates/cluster-template-azure.rc, templates/cluster-template-azure.yaml, templates/cluster-template-gcp.rc, templates/cluster-template-gcp.yaml, templates/cluster-template-openstack.rc, templates/cluster-template-openstack.yaml
The fields `riskLevel` and `confinement` were not read from the spec before. Now we patch them to be read here,
Tested locally by deploying a cluster on Openstack with new risk level and confinement.
=> Fix reading risklevel and confinement from spec

apis/v1beta1/microk8sconfig_types.go, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml, controllers/cloudinit/cloudinit_common_test.go, controllers/cloudinit/controlplane_init.go, controllers/cloudinit/controlplane_init_test.go, controllers/cloudinit/controlplane_join.go, controllers/cloudinit/controlplane_join_test.go, controllers/cloudinit/embed.go, controllers/cloudinit/scripts/00-configure-snapstore-proxy.sh, controllers/cloudinit/worker_join.go, controllers/cloudinit/worker_join_test.go, controllers/microk8sconfig_controller.go
If the user sets the two SnapstoreProxyDomain SnapstoreProxyId configuration options the snapd registers to the designated snapstore proxy.
Tested manually based on the instructions in https://docs.ubuntu.com/snap-store-proxy/en/install. In short, in a VM next to the CAPI cluster do:
```
sudo snap install snap-store-proxy
sudo apt install postgresql
```
Get the IP or host endpoint and put it in:
```
sudo snap-proxy config proxy.domain=<IP or host domain>
```
Configure postgress with something like:
```
$ cat ./ps.sql 
CREATE ROLE "snapproxy-user" LOGIN CREATEROLE PASSWORD 'snapproxy-password';
CREATE DATABASE "snapproxy-db" OWNER "snapproxy-user";
\connect "snapproxy-db"
CREATE EXTENSION "btree_gist";
```
and
```
sudo -u postgres psql < ps.sql 
sudo snap-proxy config …
```
=> Introduce two snapstore proxy configuration options

templates/cluster-template-azure.yaml
There were some errors with change in phase of the machine (particularly the CP machines) from `Provisioned` to `Ready`. This was fixed by introducing the IPinIP conifuration to `true` in Control Plane machine templates.
Tested locally by calling cluster up and down multiple times.
=> IPinIp config for azure cluster templates

controllers/cloudinit/scripts/20-microk8s-join.sh
=> Fix typo in cloud-init bash scripts

templates/cluster-template-maas.rc, templates/cluster-template-maas.yaml
Add cluster-template using the maas cluster API provider https://github.com/spectrocloud/cluster-api-provider-maas
=> Add cluster template for MaaS

templates/cluster-template-openstack.rc, templates/cluster-template-openstack.yaml
Update OpenStack Cluster template
Replaces #80 
- Add support for using an Octavia LoadBalancer for the control plane endpoint through an option (`OPENSTACK_USE_OCTAVIA_LOADBALANCER=true`)
- Update to latest API version of the openstack cluster template (v1alpha5 is deprecated and will be removed)
=> Update OpenStack cluster template

controllers/cloudinit/scripts/00-install-microk8s.sh
Do not try to install microk8s if it's already installed on the machine.
=> skip snap install if microk8s already installed

controllers/cloudinit/controlplane_join.go, controllers/cloudinit/controlplane_join_test.go, controllers/cloudinit/scripts/20-microk8s-join.sh, controllers/cloudinit/worker_join.go, controllers/cloudinit/worker_join_test.go, controllers/microk8sconfig_controller.go
Make sure that we use an IP address for the microk8s join commands. This is done by filtering for addresses of type `InternalIP` or `ExternalIP`.
- Update `getControlPlaneNodesToJoin` to group the list of control plane addresses by type, then return a list of addresses of the same type. The order of preference is defined as `InternalIP`, then `ExternalIP`. We return the first list of addresses that is not empty.
- Do not use a `[2]string` for the join addresses, but rather return the full slice of found addresses.
- Adjust the `20-microk8s-join.sh` script to accept any number of join urls, not hardcoded to two.
- If no node IPs are found, we print an error and list the addresses that we found (hopefully this should be clear enough in case no IP is set on the machine addresses).
=> ensure we use InternalIP or ExternalIP machine addresses

controllers/microk8sconfig_controller.go
We keep using `"crt"` and `"key"` everywhere else, but also make sure to set the right secret fields
=> set tls.crt and tls.key on the cluster CA secret

templates/cluster-template-aws.rc, templates/cluster-template-aws.yaml
Update infrastructure to v1beta2 because v1beta1 is deprecated (https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v2.4.0).
=> Change AWS custom resources api version in cluster-template-aws.yaml

main.go
**What this PR does / why we need it:** This PR adds support for watchNamespace flag for bootstrap-microk8s controller which will restrict the controller to watch cluster-api objects in its namespace only. This is beneficial for certain downstream use cases where there is a separation between controllers and webhooks and one controller is used per namespace.
**Fixes:**
#94
=> Support watchNamespace for controller

apis/v1beta1/microk8sconfig_types.go, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml, config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml, controllers/cloudinit/cloudinit_common_test.go, controllers/cloudinit/controlplane_init.go, controllers/cloudinit/controlplane_init_test.go, controllers/cloudinit/controlplane_join.go, controllers/cloudinit/controlplane_join_test.go, controllers/cloudinit/scripts/00-configure-snapstore-proxy.sh, controllers/cloudinit/worker_join.go, controllers/cloudinit/worker_join_test.go, controllers/microk8sconfig_controller.go
Adds a new SnapStoreProxyScheme field to the Microk8sConfig type.
This field is meant to be either `http` or `https` without `://`. For backwards-compatibility reasons this new field has been added because the existing field was called `SnapstoreProxyDomain` and I do not think it's appropriate for a variable with that name to specify the URL scheme.
This addresses https://github.com/canonical/cluster-api-bootstrap-provider-microk8s/issues/108
=> add new SnapstoreProxyScheme field

controllers/cloudinit/scripts/00-configure-snapstore-proxy.sh
removes the need to restart from preRunCommands like in this example manifest:
```
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: MicroK8sConfigTemplate
metadata:
name: microk8s-maas-md-0
namespace: default
spec:
template:
spec:
initConfiguration:
preRunCommands:
- |
cat > /usr/local/share/ca-certificates/pcr_ca.crt << EOF
...
EOF
sudo update-ca-certificates
curl -sL .../auth/store/assertions | snap ack /dev/stdin
snap set core proxy.store=...
sudo systemctl restart snapd
```
From what I've seen of users configurations they setup the proxy with https manually in preRunCommands, and the last command is a systemctl restart snapd. If they don't restart snapd after setting up certificates snap install fails with an SSL error.
Before 0.6.9 we hardcoded the proxy protocol as http, so we …
=> restart snapd after configuring proxy

README.md, integration/README.md, integration/cluster-manifests/cluster-disable-default-cni.yaml, integration/cluster-manifests/cluster-inplace.yaml, integration/cluster-manifests/cluster.yaml, integration/e2e_test.go, templates/cluster-template-aws.yaml
Added tests with disableDefaultCNI set to true for change #110  and improved loging.
Readme fixes.
KU-1226
=> Integration test for disable default cni flag

Dockerfile, controllers/cloudinit/cloudinit.go, controllers/cloudinit/controlplane_init.go, controllers/cloudinit/controlplane_init_test.go, controllers/cloudinit/controlplane_join.go, controllers/cloudinit/controlplane_join_test.go, controllers/microk8sconfig_controller.go, pkg/token/token.go, pkg/token/token_test.go
This PR adds the `/capi/etc/token` file with a random token to the control plane machines.
1. Cluster agent token validation --> https://github.com/canonical/microk8s-cluster-agent/pull/56
2. Microk8s bootstrap provider add token file and secret --> This one
3. Microk8s control plane provider use token for request --> https://github.com/canonical/cluster-api-control-plane-provider-microk8s/pull/68
4. Merging `dqlite-remove-endpoint` feature branch to main:
a. cluster-agent: https://github.com/canonical/microk8s-cluster-agent/pull/57
b. control-plane provider: https://github.com/canonical/cluster-api-control-plane-provider-microk8s/pull/69
=> Add capi-auth-token file to control plane machines

controllers/cloudinit/scripts/20-microk8s-join.sh, integration/cluster-manifests/cluster.yaml
This prevents situations where the join fails indefinitely and we can not see anything in the logs.
Also changed the number of control plane replicas in default `cluster.yaml` manifest for e2e tests since we're testing rolling upgrades with that manifest.
=> chore(join): Limit join retry attempts
