canonical/cluster-api-bootstrap-provider-microk8s

apis/v1beta1/condition_const.go

This PR removes a couple of unused constants from the bootstrap provider codebase

Remove unused constants

---

apis/controlplane/v1beta1/microk8scontrolplane_types.go
apis/controlplane/v1beta1/zz_generated.deepcopy.go
config/crd/bases/controlplane.bootstrap.cluster.x-k8s.io_microk8scontrolplanes.yaml

This PR removes some fields in the config status object that are not used

Cleanup failure configs

---

controllers/cloudinit/controlplane_init.go
controllers/cloudinit/controlplane_join.go

We move the API server port and endpoint to 6443. Fixes workloads in need to talk to the API server.

Rework cloud-inits to have the apiserver on 6443

---

.vscode/launch.json
apis/controlplane/v1beta1/microk8scontrolplane_types.go
apis/v1beta1/condition_const.go
apis/v1beta1/microk8sconfig_types.go
apis/v1beta1/microk8sconfigtemplate_types.go
controllers/cloudinit/cloudinit.go
controllers/cloudinit/cloudinit_test.go
controllers/cloudinit/controlplane_init.go
controllers/cloudinit/controlplane_join.go
controllers/cloudinit/controlplane_test.go
controllers/cloudinit/utils.go
controllers/cloudinit/worker_join.go
controllers/locking/control_plane_init_mutex.go
controllers/locking/control_plane_init_mutex_test.go
main.go

No functional changes. Just minor edits on certificates updates in the files and removing the boilercode from kubebuilder.
Signed-off-by: Sachin Kumar Singh <sachin.singh@canonical.com>

Minor formatting changes for certificates and boilercode removal

---

apis/v1beta1/microk8sconfig_types.go
bootstrap-components.yaml
config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml
config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml
controllers/cloudinit/cloudinit_test.go
controllers/cloudinit/controlplane_init.go
controllers/cloudinit/controlplane_join.go
controllers/cloudinit/utils.go
controllers/microk8sconfig_controller.go
examples/aws-capi-quickstart.yaml
templates/cluster-template-aws.yaml

IPinIP option in the initConfiguration of nodes

Working calico ipip configuration

---

controllers/cloudinit/controlplane_init.go
controllers/cloudinit/controlplane_join.go
controllers/cloudinit/worker_join.go

Disable kubelet and containerd services running from the host image (if any)

Disable host image kubelet and containerd services

---

integration/test.sh

Goes along with https://github.com/charmed-kubernetes/jenkins/pull/1062

Add integration tests for CI

---

integration/test.sh

Minor PR to improve debugging during integration tests

Increase visibility into cluster during integration tests

---

integration/README.md
integration/test.sh

Move the AWS specific sections outside the test.

Make the integration test cloud agnostic

---

integration/README.md

Added instructions to configure your local setup for running the integration test.
Signed-off-by: Sachin Kumar Singh <sachin.singh@canonical.com>

Add instructions for doing a local test

---

README.md
go.mod
go.sum
templates/cluster-template-azure.rc
templates/cluster-template-azure.yaml

Added a new template for azure using CAPZ.
Signed-off-by: Sachin Kumar Singh <sachin.singh@canonical.com>

Cluster template for azure

---

config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml
config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml

Follow up PR for #47, regenerate CRDs to include new options

Regenerate CRDs to include RiskLevel config

---

apis/v1beta1/microk8sconfig_types.go
bootstrap-components.yaml
config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml
config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml

Enforce lowerCamelCase casing in all new API fields

Enforce proper casing in API fields

---

README.md
templates/cluster-template-gcp.rc
templates/cluster-template-gcp.yaml

Add instructions and a cluster template for deploying MicroK8s on GCP

Add GCP cluster template

---

metadata.yaml

Signed-off-by: Sachin Kumar Singh <sachin.singh@canonical.com>

Update to 0.3.0

---

metadata.yaml

metadata.yaml has to include the past releases

Include past releases in metadata.yaml

---

integration/README.md
integration/e2e_test.go

Added e2e tests for `inPlace` upgrades.  Also did some refactoring to make it easy if and when we want different tests for different upgrade strategies.

Add e2e tests for in-place upgrades

---

apis/v1beta1/microk8sconfig_types.go
config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigs.yaml
config/crd/bases/bootstrap.cluster.x-k8s.io_microk8sconfigtemplates.yaml
controllers/cloudinit/cloudinit_common_test.go
controllers/cloudinit/controlplane_init.go
controllers/cloudinit/controlplane_init_test.go
controllers/cloudinit/controlplane_join.go
controllers/cloudinit/controlplane_join_test.go
controllers/cloudinit/embed.go
controllers/cloudinit/scripts/00-configure-snapstore-http-proxy.sh
controllers/cloudinit/worker_join.go
controllers/cloudinit/worker_join_test.go
controllers/microk8sconfig_controller.go

Add `snapstoreHTTPProxy` and `snapstoreHTTPSProxy` configurations

Add support for snap store HTTP proxy configuration

---

controllers/cloudinit/scripts/00-install-microk8s.sh

Fix regression introduced in #86

check if microk8s is installed

---

templates/cluster-template-aws.rc
templates/cluster-template-azure.rc
templates/cluster-template-gcp.rc
templates/cluster-template-openstack.rc

QOL change, set default values for risk level and confinement

Use default risk level and confinement on templates

---

templates/cluster-template-maas.yaml

Follow up work on #89, make the tags optional

make maas machine tags optional

---

Makefile

Reverts canonical/cluster-api-bootstrap-provider-microk8s#116

Revert "Increase golangci lint version"

---

.github/.jira_sync_config.yaml

CI: add jirasync for gh issues
